dist: trusty
language: tex
sudo: false

install:
  - cp -n texlive* /tmp/
  - source /tmp/texlive_install.sh
  - tlmgr install koma-script etoolbox logreq biblatex-apa csquotes siunitx oberdiek tocloft abstract pdfpages enumitem psnfss ms caption ec l3kernel l3packages zapfding symbol helvetic textpos glossaries xkeyval mfirstuc textcase xfor datatool substr fp tracklang

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script:
  - source .version

script:
  - pdflatex -interaction=nonstopmode -halt-on-error BDA_FS19_Projektdokumentation.tex
  - biber *.bcf
  - makeglossaries BDA_FS19_Projektdokumentation
  - pdflatex -interaction=nonstopmode -halt-on-error BDA_FS19_Projektdokumentation.tex
  - pdflatex -interaction=nonstopmode -halt-on-error "\providecommand{\docversion}{${VERSION}.${TRAVIS_BUILD_NUMBER}} \input{BDA_FS19_Projektdokumentation.tex}"

deploy:
  - provider: releases
    api_key: $GIT_AUTH
    skip_cleanup: true
    prerelease: true
    file: "BDA_FS19_Projektdokumentation.pdf"
    tag_name: "v${VERSION}.${TRAVIS_BUILD_NUMBER}"
    name: "v${VERSION}.${TRAVIS_BUILD_NUMBER}"
    on:
      tags: false
      branch: "master"
  - provider: releases
    api_key: $GIT_AUTH
    skip_cleanup: true
    file:
      - "BDA_FS19_Projektdokumentation.pdf"
    on:
      tags: true
